name: document_scanner
description: fiurthorn document scanner

publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: any
  http: any
  image: ^4.0.17

dependencies:
  args: ^2.4.0
  async: ^2.9.0
  crop_your_image: ^0.7.5
  cunning_document_scanner: ^1.1.2
  equatable: ^2.0.0
  file_picker: ^5.2.5
  file_saver: ^0.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_form_bloc: ^0.30.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  get_it: ^7.2.0
  glob: ^2.1.1
  go_router: ^10.0.0
  hive: ^2.0.2
  image: ^4.0.17
  image_picker: ">=0.8.9 <2.0.0"
  intl: any
  mime: ^1.0.4
  mobile_scanner: ^3.3.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  pdfx: ^2.4.0
  source_map_stack_trace: ^2.1.1
  source_maps: ^0.10.12
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.0.6
  dependency_validator: ^3.2.2
  flutter_launcher_icons_maker: "any"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: any
  json_serializable: ^6.1.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - icons/
    - icons/transparent/
    - icons/filled/

flutter_icons:
  image_path: "icons/transparent/xxxhdpi.png"
  android: true
