name: document_scanner
description: fiurthorn document scanner

publish_to: "none"

version: 0.3.0+18

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  intl: any
  http: any
  image: ^4.0.17

dependencies:
  args: ^2.4.0
  async: ^2.9.0
  crop_your_image: ^0.7.5
  cunning_document_scanner: ^1.1.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.0
  file_picker: ^5.2.5
  file_saver: ^0.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.4.1
  get_it: ^7.2.0
  glob: ^2.1.1
  go_router: ^11.1.4
  google_mlkit_text_recognition: ^0.10.0
  hive: ^2.0.2
  image: ^4.0.17
  image_picker: ">=0.8.9 <2.0.0"
  intl: any
  mime: ^1.0.4
  mobile_scanner: ^3.3.0
  path: ^1.8.3
  pdf: ^3.10.4
  pdfx: ^2.4.0
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  reactive_date_time_picker: ^3.0.0
  reactive_forms: ^16.1.0
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.0.6
  dependency_validator: ^3.2.2
  flutter_launcher_icons: "any"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: any
  json_serializable: ^6.1.1
  mockito: ^5.3.2
  test: ^1.24.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - icons/
    - ChangeLog.md

flutter_icons:
  image_path: "icons/logo.png"
  android: true
